keywords    = "Go,MVC,HTTPServer,TCPServer,UDPServer,WebServer,Cookie,Session,ORM,golang,cache,goframe, go frame,gf"
description = "模块化、松耦合、轻量级、高性能的Go语言Web开发框架。支持热重启、热更新、多域名、多端口、多服务、HTTP/HTTPS、动态路由等特性，并提供了Web服务开发的系列核心组件，如：Router、Cookie、Session、服务注册、配置管理、模板引擎、数据校验、分页管理、数据库ORM等等等等，并且提供了数十个实用开发模块集，如：缓存、日志、时间、命令行、二进制、文件锁、对象池、连接池、数据编码、进程管理、进程通信、TCP/UDP组件、并发安全容器、Goroutine池等等等等等等。"

# Server设置
[server]
    Address    = ":8199"
    LogPath    = "/tmp/gf-home/server"
    ServerRoot = "public"
    SearchPaths = ["D:/Workspace/Go/GOPATH/src/github.com/gogf/gf-doc"]

# 日志设置
[logger]
    path   = "/tmp/gf-home"
    level  = "all"
    stdout = false

# 开发文档设置
[document]
    title = "GoFrame框架开发文档 - Powered by GoFrame"
    path  = "D:/Workspace/Go/GOPATH/src/github.com/gogf/gf-doc"
    hook  = "pass"

# 初始化项目配置
[project]
    url  = "https://github.com/gogf/gf-empty/archive/master.zip"

# 版本管理地址
[git]
	gitee  = "https://gitee.com/johng/gf"
	github = "https://github.com/gogf/gf"

# CLI二进制文件
[cli]
    path = "D:/Workspace/Go/GOPATH/src/github.com/gogf/gf-cli/bin"

# CDN配置
[cdn]
    url     = "https://cdn.goframe.org"
    version = "v=1"



